Scripts recursively display error lines

diff --git a/src/core/scripts/noelle-meta-clean b/src/core/scripts/noelle-meta-clean
--- a/src/core/scripts/noelle-meta-clean
+++ b/src/core/scripts/noelle-meta-clean
@@ -1,8 +1,10 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 if test $# -lt 2 ; then
-  echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE" ;
-  exit 1;
+  echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE"
+  exit 1
 fi
 
 noelle-load --strip-named-metadata -MetadataCleaner -clean-loop-metadata -clean-prof-metadata -clean-pdg-metadata -clean-pdg-scc-metadata $@
diff --git a/src/core/scripts/noelle-meta-prof-clean b/src/core/scripts/noelle-meta-prof-clean
--- a/src/core/scripts/noelle-meta-prof-clean
+++ b/src/core/scripts/noelle-meta-prof-clean
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 if test $# -lt 2 ; then
   echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE"
   exit 1
diff --git a/src/core/scripts/noelle-norm.in b/src/core/scripts/noelle-norm.in
--- a/src/core/scripts/noelle-norm.in
+++ b/src/core/scripts/noelle-norm.in
@@ -1,4 +1,6 @@
-#!/bin/bash -ex
+#!/bin/bash -e
+
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
 opt @noelle_norm_OPT_ARGS@ $@
 
diff --git a/src/tools/scripts/noelle-deadcode b/src/tools/scripts/noelle-deadcode
--- a/src/tools/scripts/noelle-deadcode
+++ b/src/tools/scripts/noelle-deadcode
@@ -1,10 +1,10 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 # delete dead functions until a fixed point is reached
-echo "NOELLE: DeadFunctions: Start" ;
+echo "NOELLE: DeadFunctions: Start"
 
-set -x
 noelle-fixedpoint $1 $2 "noelle-load" -DeadFunctionEliminator ${@:3}
-set +x
 
-echo "NOELLE: DeadFunctions: Exit" ;
+echo "NOELLE: DeadFunctions: Exit"
diff --git a/src/tools/scripts/noelle-privatizer b/src/tools/scripts/noelle-privatizer
--- a/src/tools/scripts/noelle-privatizer
+++ b/src/tools/scripts/noelle-privatizer
@@ -1,10 +1,10 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 # run the privatizer until a fixed point is reached
 echo "NOELLE: Privatizer: Start"
 
-set -x
 noelle-fixedpoint $1 $1 "noelle-load" -privatizer ${@:2}
-set +x
 
-echo "NOELLE: Privatizer: Exit" ;
+echo "NOELLE: Privatizer: Exit"
diff --git a/src/tools/scripts/noelle-rm-function b/src/tools/scripts/noelle-rm-function
--- a/src/tools/scripts/noelle-rm-function
+++ b/src/tools/scripts/noelle-rm-function
@@ -1,11 +1,8 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 # delete dead functions until a fixed point is reached
-
 echo "NOELLE: DeadFunctions: Start"
-
-set -x
 noelle-load -noelle-rm-function $@
-set +x
-
 echo "NOELLE: DeadFunctions: Exit"
